# Generated by Django 5.2.4 on 2025-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="transaction_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
