# Generated by Django 5.2.4 on 2025-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_transaction_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="transaction_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
