# Generated by Django 5.2.4 on 2025-07-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_eth_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("seller", "Seller"),
                    ("appraiser", "Appraiser"),
                    ("inspector", "Inspector"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
